---
# Dieses Playbook installiert das Programm HUS Struktogrammer. Das Paket des Herstellers 
# ist weder über die Debian-Repositories noch über Flathub verfügbar und kann daher nur 
# direkt beim Hersteller bezogen werden.

- hosts: localhost
  connection: local
  become: true

  tasks:
   - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - default-jre
          - tar
        state: present
   #   when: ansible_os_family == "Debian"

    - name: Download Struktogrammer installer
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/struktogrammer/files/InstallStgr_Linux.tar.gz/download
        dest: /tmp/InstallStgr_Linux.tar.gz
        mode: '0644'

    - name: Extract installer archive
      ansible.builtin.unarchive:
        src: /tmp/InstallStgr_Linux.tar.gz
        dest: /tmp/struktogrammer_installer
        remote_src: yes
        creates: /tmp/struktogrammer_installer

    - name: Run installer script
      ansible.builtin.command: ./install.sh
      args:
        chdir: /tmp/struktogrammer_installer
      register: install_output

    - name: Debug installation output (optional)
      ansible.builtin.debug:
        var: install_output.stdout

    - name: Create desktop entry
      ansible.builtin.copy:
        dest: /usr/share/applications/struktogrammer.desktop
        mode: '0644'
        content: |
          [Desktop Entry]
          Version=1.0
          Name=HUS Struktogrammer
          Comment=Programmieren mit Struktogrammen
          Exec=/usr/local/bin/struktogrammer
          Icon=/opt/struktogrammer/stgr.png
          Terminal=false
          Type=Application
          Categories=Education;Development;
