---
- hosts: localhost
  connection: local
  become: true
#  vars: 
#    flatpakrepo: https://dl.flathub.org/repo/flathub.flatpakrepo/appstream/

  tasks:
  - name: Installiere Pakete aus dem Debian-Repository
    package:
      name: 
        - arduino                               # Arduino 1
        - emacs                                 # Emacs
        - gedit                                 # GNOME-Editor
        - kate                                  # KDE Editor
        - veyon-configurator                    # Veyon für Schülergeräte
        - chromium                              # Chromium-Browser, benötigt für LEGO Spike web App etc.
        - shotcut                               # einfaches Videoschnitt-Programm
        - python-is-python3                     # Python  
        - python3-psutil
        - inkscape                              # Vektorgrafik
#        - filius                                # Filius Rechnernetzwerke - Paket wurde entfernt

#  - name: Synchronisiere die Hersteller-Pakete in ein lokales Verzeichnis des Administrators
#    ansible.posix.synchronize:
#      src: /home/holgervoss/dev/packages/
#      dest: /home/administrator/packages/

#  - name: Installiere die Hersteller-Pakete
#    ansible.builtin.apt:
#      deb: /home/administrator/packages/MindPlus/MindPlus_1.7.3-202307011900_amd64_x86.deb
#      deb: /home/administrator/packages/Structorizer/structorizer_3.32-19.deb
#      deb: http://public.dzogovic.org/structorizer_3.23.deb

  - name: Installiere Flatpak
    package:
      - name:
        - flatpak                               # Flatpak + GNOME Software-Plugin
        - gnome-software-plugin-flatpak
      deb: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Installiere Flatpak-Pakete
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2            # TigerJython Programmier-Lernumgebung für Python
        - de.lernsoftware_filius.Filius          # Filius Netwerkbau
        - org.eclipse.Java                       # Eclipse Java-Editor
        - org.processing.processingide           # Processing Java-Editor 
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Microsoft Visual Studio
        - edu.mit.Scratch                        # Scratch 3 (deb-Paket ist veraltet)
        - com.github.PintaProject.Pinta          # Pendant zu Paint in der Windows-Welt
        - cc.arduino.IDE2                        # Arduino 2
        - org.bluej.BlueJ                        # BlueJ Java-Editor
      state: present
