---
# Dieses Skript enthält die Software-Grundausstattung der PC-Räume, soweit sie über Debian oder Flatpak verfügbar ist. Es erzeugt zudem einen Cronjob,
# der dieses Script alle 10 Minuten neu über Github aufruft. Nach erstmaliger Ausführung des Skriptes über ssh ist also keine weitere manuelle Ausführung 
# erforderlich, da Änderungen am Skript auf Github bei Nutzung der Rechner automatisch nach 10 Minuten von den Clients übernommen werden. Ein Schlüssel
# ist nicht erforderlich, da das Playbook öffentlich im Netz steht. Das Installieren, Aktualisieren oder auch Löschen von Software kann so einmalig im 
# Playbook informatik.yml vorgenommen werden und wird dann automatisch auf alle Clients ausgerollt. Diese Vorgänge finden im Hintergrund statt 
# und stören die Arbeit an den Clients in der Regel nicht.

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installiere die Sprachpakete des Systems und des Desktops
    package:
      name: 
#        - language-pack-de
        - task-german 
        - task-german-desktop
      state: latest
      update_cache: yes

  - name: Installiere den Chromium-Browser in der Debian-Distribution.
    package:
      - chromium                                # Chromium-Browser, benötigt für LEGO Spike web App etc.
      - chromium-l10n                           # Chromium-Sprachlokalisation
    when: ansible_facts['distribution'] == "Debian"
    state: latest

  - name: Installiere Anwendungen aus dem Debian-Repository
    package:
      name: 
        - arduino                               # Arduino 1
        - emacs                                 # Emacs
        - gedit                                 # GNOME-Editor
        - kate                                  # KDE Editor
#        - veyon-configurator                    # aktuellere Version erforderlich
#        - veyon-plugins
#        - veyon-service
        - x11vnc                                # VNC-Server für X11
        - gnome-connections                     # RDP / VNC-Verbindung
#        - chromium #-browser                      # Chromium-Browser, benötigt für LEGO Spike web App etc.
#        - chromium-l10n # browser-l10n                 # Chromium-Sprachlokalisation
        - shotcut                               # einfaches Videoschnitt-Programm
        - thonny                                # Python für Einsteiger
        - python-is-python3                     # Python  
        - python3-psutil                        # Abrufen von Informationen über laufende Prozesse
        - inkscape                              # Vektorgrafik
        - catfish                               # Datei- und Volltextsuche
        - flatpak                               # Flatpak 
        - gnome-software-plugin-flatpak         # Integration von Flatpak in GNOME
        - gnome-tweaks                          # GNOME-Optimierungen
#        - kolourpaint                           # Malprogramm
        - libreoffice
        - libreoffice-l10n-de
      state: latest

  - name: Deinstalliere Spiele aus dem Debian-Repository
    package:
      name: 
        - aisleriot
        - 2048
        - iagno
        - robots
        - mahjongg
        - mines
        - sudoku
        - five-or-more
        - hitori
        - four-in-a-row
        - klotski
        - lightsoff 
        - nibbles
        - quadrapassel
        - swell-foop
        - tetravex
        - taquin
        - tali
        - gnome-aisleriot
        - gnome-2048
        - gnome-lightsoff
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - gnome-five-or-more
        - gnome-hitori
        - gnome-four-in-a-row
        - gnome-klotski 
        - gnome-nibbles
        - gnome-quadrapassel
        - gnome-iagno
        - gnome-robots
        - gnome-swell-foop
        - gnome-tetravex
        - gnome-taquin
        - gnome-tali
      state: absent

  - name: Füge das Flathub Flatpak Repository zur System-Installation hinzu
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Installiere Anwendungen aus dem Flathub-Repository
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2            # TigerJython Programmier-Lernumgebung für Python
        - de.lernsoftware_filius.Filius          # Filius Netwerkbau
        - org.eclipse.Java                       # Eclipse Java-Editor
        - org.processing.processingide           # Processing Java-Editor 
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Microsoft Visual Studio
        - edu.mit.Scratch                        # Scratch 3 (deb-Paket ist veraltet)
        - com.github.PintaProject.Pinta          # Pendant zu Paint in der Windows-Welt
        - cc.arduino.IDE2                        # Arduino 2
        - org.bluej.BlueJ                        # Java-Editor
        - com.jetbrains.IntelliJ-IDEA-Community  # Java und Kotlin-Editor
        - com.vscodium.codium                    # Java und Visual Studio Editor
        - io.github.pemsley.coot                 # Makromoleküle bauen
      state: present

  - name: Stelle sicher, dass der Cronjob-Daemon läuft
    ansible.builtin.systemd_service:
      state: started
      name: cron
      daemon_reload: true
      enabled: true

  - name: Füge den Ansible-pull Cronjob hinzu
    ansible.builtin.cron: 
      name: ansible auto-provision
      user: root
      minute: "*/10"
      hour: "*"
      day: "*"
      job: sudo ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git informatik.yml
 
  - name: Entferne überflüssigen Nutzer 'velociraptor'
    ansible.builtin.user:
      name: velociraptor
      state: absent
      remove: yes
