---
# Dieses Skript enthält die Software-Grundausstattung der PC-Räume, soweit sie über Debian oder Flatpak verfügbar ist. Es erzeugt zudem einen Cronjob,
# der dieses Script alle 10 Minuten neu über Github aufruft. Nach erstmaliger Ausführung des Skriptes über ssh ist also keine weitere manuelle Ausführung 
# erforderlich, da Änderungen am Skript auf Github bei Nutzung der Rechner automatisch nach 10 Minuten von den Clients übernommen werden. Ein Schlüssel
# ist nicht erforderlich, da das Playbook öffentlich im Netz steht. Das Installieren, Aktualisieren oder auch Löschen von Software kann so einmalig im 
# Playbook informatik.yml vorgenommen werden und wird dann automatisch auf alle Clients ausgerollt. Diese Vorgänge finden im Hintergrund statt 
# und stören die Arbeit an den Clients in der Regel nicht.

- hosts: localhost
  connection: local
  become: true
  
#  environment: 
#    http_proxy: http://hg-gym.de/proxy.pac

  tasks:
  
  - name: Stelle sicher, dass der Cronjob-Daemon läuft
    ansible.builtin.systemd_service:
      state: started
      name: cron
      daemon_reload: true
      enabled: true

  - name: Füge den Ansible-pull Cronjob hinzu
    ansible.builtin.cron: 
      name: ansible auto-provision
      user: root
      minute: "*/10"
      hour: "*"
      day: "*"
      job: sudo ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git informatik.yml

  - name: Erzeuge eine Gruppe 'Hainberg'
    ansible.builtin.group:
      name: hainberg
      gid: 1200
      state: present

  - name: Erzeuge einen Nutzer 'Hainberg' mit einem eigenen Home-Verzeichnis
    ansible.builtin.user:
      name: hainberg
      comment: "Hainberg"
      group: hainberg
      create_home: yes
      state: present
      password: "{{ 'hainberg' | password_hash('sha512') }}"
      update_password: always

  - name: Installiere die Sprachpakete des Systems und des Desktops
    package:
      name: 
        - task-german 
        - task-german-desktop
      state: latest
      update_cache: yes

  - name: Installiere den Chromium-Browser und andere distributionsspezifische Pakete in Debian.
    package:
      name:
        - chromium                                # Chromium-Browser, benötigt für LEGO Spike web App etc.
        - chromium-l10n                           # Chromium-Sprachlokalisation
      state: latest
#    when: ansible_facts['distribution'] == "Debian"


#  - name: Installiere den Chromium-Browser und andere distributionsspezifische Pakete in Ubuntu.
#    package:
#      name:
#        - chromium-browser                        # Chromium-Browser, benötigt für LEGO Spike web App etc.
#        - chromium-browser-l10n                   # Chromium-Sprachlokalisation
#        - language-pack-de                        # deutsches Sprachpaket für Ubuntu
#      state: latest
#    when: ansible_facts['distribution'] == "Ubuntu"


  - name: Installiere Anwendungen aus dem Debian-Repository
    package:
      name: 
        - arduino                               # Arduino 1
        - emacs                                 # Emacs
        - gedit                                 # GNOME-Editor
        - gimp					# professionelle Bildbearbeitung
        - gwenview				# einfache Bildbearbeitung
        - kate                                  # KDE Editor
        - x11vnc                                # VNC-Server für X11
        - gnome-connections                     # RDP / VNC-Verbindung
        - shotcut                               # einfacher Videoschnitt
        - thonny                                # Python für Einsteiger
        - python-is-python3                     # Python  
#        - python3-keras                         # ... sowie weitere Python-Module
        - python3-keras-applications
        - python3-keras-preprocessing
        - python3-psutil                       
        - python3-numpy                       
        - python3-pygame
        - python3-matplotlib
        - python3-pip
        - python3-venv
        - inkscape                              # Vektorgrafik
        - catfish                               # Datei- und Volltextsuche
        - flatpak                               # Flatpak 
        - gnome-software-plugin-flatpak         # Integration von Flatpak in GNOME
        - gnome-tweaks                          # GNOME-Optimierungen
        - libreoffice
        - libreoffice-l10n-de
      state: latest

  - name: Deinstalliere Spiele aus dem Debian-Repository
    package:
      name: 
        - aisleriot
        - 2048
        - iagno
        - robots
        - mahjongg
        - mines
        - sudoku
        - five-or-more
        - hitori
        - four-in-a-row
        - klotski
        - lightsoff 
        - nibbles
        - quadrapassel
        - swell-foop
        - tetravex
        - taquin
        - tali
        - gnome-aisleriot
        - gnome-2048
        - gnome-lightsoff
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - gnome-five-or-more
        - gnome-hitori
        - gnome-four-in-a-row
        - gnome-klotski 
        - gnome-nibbles
        - gnome-quadrapassel
        - gnome-iagno
        - gnome-robots
        - gnome-swell-foop
        - gnome-tetravex
        - gnome-taquin
        - gnome-tali
      state: absent

  - name: Füge das Flathub Flatpak Repository zur System-Installation hinzu
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Installiere Anwendungen aus dem Flathub-Repository
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2            # TigerJython Programmier-Lernumgebung für Python
        - de.lernsoftware_filius.Filius          # Filius Netwerkbau
        - org.eclipse.Java                       # Eclipse Java-Editor
        - org.processing.processingide           # Processing Java-Editor 
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Microsoft Visual Studio
        - edu.mit.Scratch                        # Scratch 3 (deb-Paket ist veraltet)
        - com.github.PintaProject.Pinta          # Pendant zu Paint in der Windows-Welt
        - cc.arduino.IDE2                        # Arduino 2
        - org.bluej.BlueJ                        # Java-Editor
        - com.jetbrains.IntelliJ-IDEA-Community  # Java und Kotlin-Editor
        - com.vscodium.codium                    # Java und Visual Studio Editor
        - io.github.pemsley.coot                 # Makromoleküle bauen
        - org.localsend.localsend_app            # plattformübergreifendes Airdropping
        - org.greenfoot.Greenfoot                # integrated development environment using Java or Stride
        - com.bambulab.BambuStudio		 # 3D-Drucker für BambuLab
        - org.apache.netbeans                    # Netbeans Java-Editor
      state: present
