---
# Playbook: Grundausstattung Informatik-PC-Räume (Cinnamon)
# Debian/Ubuntu + automatische Aktualisierung via ansible-pull

- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    repo_url: "https://github.com/hvoss71/ansible_desktop.git"
    playbook_file: "informatik.yml"

  tasks:

  ###########################################################################
  # 1. Cronjob für automatische Aktualisierung
  ###########################################################################

  - name: Stelle sicher, dass der Cron-Dienst läuft
    ansible.builtin.systemd:
      name: cron
      state: started
      enabled: true

  - name: Füge Cronjob für ansible-pull hinzu
    ansible.builtin.cron:
      name: "Ansible Auto-Provision"
      user: root
      minute: "*/10"
      job: "ansible-pull -o -U {{ repo_url }} {{ playbook_file }} > /var/log/ansible-pull.log 2>&1"
      state: present

  ###########################################################################
  # 2. Benutzer- und Gruppenverwaltung
  ###########################################################################

  - name: Stelle sicher, dass die Gruppe 'hainberg' existiert
    ansible.builtin.group:
      name: hainberg
      state: present

  - name: Erzeuge lokalen Notfall-Benutzer 'hainberg-local'
    ansible.builtin.user:
      name: hainberg-local
      uid: 2001
      group: users
      create_home: yes
      shell: /bin/bash
      password: "{{ 'hainberg' | password_hash('sha512') }}"
      state: present

  ###########################################################################
  # 3. Systemupdates
  ###########################################################################

  - name: Aktualisiere Paketquellen und installiere Updates
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist

  ###########################################################################
  # 4. Anwendungen aus Debian-/Ubuntu-Repositories
  ###########################################################################

  - name: "Prüfe Distribution"
    debug:
      msg: "Distribution erkannt: {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"

  - name: "Installiere Chromium unter Debian (APT)"
    ansible.builtin.apt:
      name:
        - chromium
        - chromium-l10n
      state: present
      update_cache: yes
    when: ansible_facts.distribution == "Debian"
  
  - name: Installiere Standardanwendungen
    ansible.builtin.apt:
      name:
      
        # Entwicklung
        - arduino
        - emacs
        - kate
        - gedit
        - thonny
        - python3
        - python-is-python3
        - python3-keras-applications
        - python3-keras-preprocessing
        - python3-psutil
        - python3-numpy
        - python3-pygame
        - python3-matplotlib
        - python3-pip
        - python3-venv
        - python3-tk                        # nötig für turtle & Tkinter
        - python3-dev
        - python3-pil.imagetk
        - python3-jedi
        - python3-parso
        - python3-asttokens
        - python3-serial                    # für MicroPython / USB / Pico
        - python3-pyudev                    # für Geräteerkennung
        
        # Grafik / Multimedia
        - gimp
        - gwenview
        - inkscape
        - shotcut

        # Office
        - libreoffice
        - libreoffice-l10n-de

        # Cinnamon Desktop
        - cinnamon
        - cinnamon-common
        - nemo-fileroller
        - catfish

        # Flatpak Support
        - flatpak
        - gnome-software-plugin-flatpak
      state: present
      update_cache: yes
    ignore_errors: yes
    
  - name: Prüfe, ob Structorizer installiert ist
    ansible.builtin.command: dpkg -s structorizer
    register: structorizer_check
    failed_when: false
    changed_when: false
    
  - name: Structorizer herunterladen
    ansible.builtin.get_url:
      url: https://www.fisch.lu/Php/download.php?file=structorizer.deb
      dest: /tmp/structorizer.deb
      mode: '0644'
    when: structorizer_check.rc != 0

  - name: Structorizer installieren
    ansible.builtin.apt:
      deb: /tmp/structorizer.deb
      state: present
    when: structorizer_check.rc != 0
    become: true

  - name: Installationsdatei löschen
    ansible.builtin.file:
      path: /tmp/structorizer.deb
      state: absent
    when: structorizer_check.rc != 0

  - name: udev-Regeln für Pico/ESP32 und Calliope mini installieren
    copy:
      dest: "/etc/udev/rules.d/99-micropython.rules"
      content: |
        SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", MODE:="0666"
        SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", MODE:="0666"
        SUBSYSTEM=="tty", ATTRS{idVendor}=="1a86", MODE:="0666"
        SUBSYSTEM=="usb", ATTRS{idVendor}=="0d28", MODE:="0666"
        
  # Auf diese Weise dürfen alle Benutzer, auch ohne Zugehörigkeit zur Gruppe dialout, auf die Geräte zugreifen.
  # 
  # 0d28 = Calliope mini


  ###########################################################################
  # 5. Automatisches Entfernen aller GNOME-Spiele (Debian/Ubuntu)
  ###########################################################################

  - name: Entferne GNOME-Spiele
    ansible.builtin.apt:
      name:
        - aisleriot
        - gnome-2048
        - iagno
        - gnome-robots
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - four-in-a-row
        - five-or-more
        - hitori
        - gnome-four-in-a-row
        - gnome-klotski
        - lightsoff
        - gnome-nibbles
        - quadrapassel
        - swell-foop
        - gnome-tetravex
        - gnome-taquin
        - tali
      state: absent
      purge: true
    become: true

  ###########################################################################
  # 6. Flatpak-Integration und externe Software
  ###########################################################################

  - name: Füge Flathub-Repository hinzu (systemweit)
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
      method: system

  - name: Installiere Unterrichtssoftware über Flatpak
    community.general.flatpak:
      name:
        - ch.tigerjython.TigerJython2
        - de.lernsoftware_filius.Filius
        - org.greenfoot.Greenfoot
        - org.eclipse.Java
        - org.processing.processingide
        - com.prusa3d.PrusaSlicer
        - com.visualstudio.code
        - edu.mit.Scratch
        - com.github.PintaProject.Pinta
        - cc.arduino.IDE2
        - com.jetbrains.IntelliJ-IDEA-Community
        - com.vscodium.codium
        - com.bambulab.BambuStudio
        - org.apache.netbeans
        - org.bluej.BlueJ
        - com.jgraph.drawio.desktop
      state: present
      method: system
      
  - name: Entferne Unterrichtssoftware über Flatpak
    community.general.flatpak:
      name:
        - org.thonny.Thonny
      state: absent
      method: system


  ###########################################################################
  # 7. Systempflege
  ###########################################################################

  - name: Entferne nicht benötigte Pakete
    ansible.builtin.apt:
      autoremove: yes
      autoclean: yes

  - name: Ausgabe nach Installation
    ansible.builtin.debug:
      msg: >
        Informatik-Grundausstattung (Cinnamon) installiert.
        Das System prüft alle 10 Minuten auf Aktualisierungen über GitHub.
        Neustart empfohlen.
