---
# Dieses Playbook installiert die Software-Grundausstattung der PC-Räume, soweit sie über Debian oder Flatpak verfügbar ist.
# Es richtet zudem einen Cronjob ein, der das Playbook alle 10 Minuten automatisch über Github neu ausführt.
# Dadurch werden Änderungen am zentralen Playbook automatisch auf allen Clients übernommen.
# Ein SSH-Schlüssel ist nicht erforderlich, da das Playbook öffentlich bereitsteht.

- hosts: localhost
  connection: local
  become: true

  tasks:

  ###########################################################################
  # 1. Grundlegende Systemdienste
  ###########################################################################

  - name: Stelle sicher, dass der Cronjob-Daemon läuft
    ansible.builtin.systemd_service:
      name: cron
      state: started
      enabled: true
      daemon_reload: true

  - name: Füge den Ansible-pull Cronjob hinzu
    ansible.builtin.cron:
      name: ansible auto-provision
      user: root
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git informatik.yml > /var/log/ansible-pull.log 2>&1
      state: present

  ###########################################################################
  # 2. Benutzer- und Gruppenverwaltung
  ###########################################################################

  - name: Stelle sicher, dass die Gruppe 'hainberg' existiert
    ansible.builtin.group:
      name: hainberg
      state: present

  - name: Erzeuge lokalen Nutzer 'hainberg-local'
    ansible.builtin.user:
      name: hainberg-local
      uid: 2001
      group: users
      create_home: yes
      shell: /bin/bash
      system: no
      state: present
      password: "{{ 'hainberg' | password_hash('sha512', 'schule') }}"

  ###########################################################################
  # 3. System- und Sprachpakete
  ###########################################################################

  - name: Aktualisiere Paketquellen und installiere Updates
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist

  - name: Installiere die Sprachpakete des Systems und des Desktops
    ansible.builtin.apt:
      name:
        - task-german
        - task-german-desktop
      state: latest

  ###########################################################################
  # 4. Anwendungen aus Debian-Repositories
  ###########################################################################

  - name: Installiere Chromium und weitere Standardanwendungen
    ansible.builtin.apt:
      name:
        - chromium                                # Browser, u.a. für LEGO Spike Web App
        - chromium-l10n                           # Sprachunterstützung
        - arduino                                 # Arduino 1.x
        - emacs
        - gedit
        - gimp
        - gwenview
        - kate
        - x11vnc                                 # VNC-Server für Fernwartung
        - gnome-connections                      # RDP/VNC-Verbindungen
        - shotcut                                # einfacher Videoschnitt
        - thonny                                 # Python-IDE für Einsteiger
        - python-is-python3
        - python3-keras-applications
        - python3-keras-preprocessing
        - python3-psutil
        - python3-numpy
        - python3-pygame
        - python3-matplotlib
        - python3-pip
        - python3-venv
        - inkscape
        - catfish
        - flatpak
        - gnome-software-plugin-flatpak
        - gnome-tweaks
        - libreoffice
        - libreoffice-l10n-de
      state: latest
      update_cache: yes

  ###########################################################################
  # 5. Entferne unerwünschte Spiele
  ###########################################################################

  - name: Deinstalliere Spiele aus dem Debian-Repository
    ansible.builtin.apt:
      name:
        - aisleriot
        - 2048
        - iagno
        - robots
        - mahjongg
        - mines
        - sudoku
        - five-or-more
        - hitori
        - four-in-a-row
        - klotski
        - lightsoff
        - nibbles
        - quadrapassel
        - swell-foop
        - tetravex
        - taquin
        - tali
        - gnome-aisleriot
        - gnome-2048
        - gnome-lightsoff
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - gnome-five-or-more
        - gnome-hitori
        - gnome-four-in-a-row
        - gnome-klotski
        - gnome-nibbles
        - gnome-quadrapassel
        - gnome-iagno
        - gnome-robots
        - gnome-swell-foop
        - gnome-tetravex
        - gnome-taquin
        - gnome-tali
      state: absent

  ###########################################################################
  # 6. Flatpak-Integration und Software
  ###########################################################################

  - name: Stelle sicher, dass Flatpak installiert ist
    ansible.builtin.apt:
      name: flatpak
      state: present

  - name: Füge das Flathub Flatpak Repository hinzu
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Installiere Anwendungen aus dem Flathub-Repository
    community.general.flatpak:
      name:
        - ch.tigerjython.TigerJython2            # Python-IDE für Einsteiger
        - de.lernsoftware_filius.Filius          # Netzwerksimulation
        - org.eclipse.Java                       # Eclipse Java-IDE
        - org.processing.processingide           # Processing-IDE
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Visual Studio Code
        - edu.mit.Scratch                        # Scratch 3
        - com.github.PintaProject.Pinta          # einfache Bildbearbeitung
        - cc.arduino.IDE2                        # Arduino 2.x
        - org.bluej.BlueJ                        # Java-IDE
        - com.jetbrains.IntelliJ-IDEA-Community  # IntelliJ Community
        - com.vscodium.codium                    # Open-Source VSCode
        - io.github.pemsley.coot                 # Molekülmodellierung
        - org.localsend.localsend_app            # AirDrop-Alternative
        - org.greenfoot.Greenfoot                # Java/Stride IDE für Lernzwecke
        - com.bambulab.BambuStudio               # 3D-Druck für BambuLab
        - org.apache.netbeans                    # NetBeans Java-IDE
      state: present
      method: system

  ###########################################################################
  # 7. Systempflege
  ###########################################################################

  - name: Entferne nicht mehr benötigte Pakete
    ansible.builtin.apt:
      autoremove: yes
