---
# Dieses Playbook installiert die Software-Grundausstattung der PC-Räume für Debian- und Ubuntu-Systeme.
# Es richtet einen Cronjob ein, der das Playbook alle 10 Minuten über GitHub neu ausführt.
# Änderungen am zentralen Playbook werden dadurch automatisch auf allen Clients übernommen.

- hosts: localhost
  connection: local
  become: true

  vars:
    repo_url: "https://github.com/hvoss71/ansible_desktop.git"
    playbook_file: "informatik.yml"

  tasks:

  ###########################################################################
  # 1. Grundlegende Systemdienste
  ###########################################################################

  - name: Stelle sicher, dass der Cronjob-Daemon läuft
    ansible.builtin.systemd_service:
      name: "{{ 'cron' if ansible_facts['os_family'] == 'Debian' else 'cron' }}"
      state: started
      enabled: true
      daemon_reload: true

  - name: Füge den Ansible-pull Cronjob hinzu
    ansible.builtin.cron:
      name: ansible auto-provision
      user: root
      minute: "*/10"
      job: "ansible-pull -o -U {{ repo_url }} {{ playbook_file }} > /var/log/ansible-pull.log 2>&1"
      state: present

  ###########################################################################
  # 2. Benutzer- und Gruppenverwaltung
  ###########################################################################

  - name: Stelle sicher, dass die Gruppe 'hainberg' existiert
    ansible.builtin.group:
      name: hainberg
      state: present

  - name: Erzeuge lokalen Nutzer 'hainberg-local'
    ansible.builtin.user:
      name: hainberg-local
      uid: 2001
      group: users
      create_home: yes
      shell: /bin/bash
      system: no
      state: present
      password: "{{ 'hainberg' | password_hash('sha512', 'schule') }}"

  ###########################################################################
  # 3. System- und Sprachpakete
  ###########################################################################

  - name: Aktualisiere Paketquellen und installiere Updates
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist

  - name: Installiere Sprachpakete für Debian oder Ubuntu
    ansible.builtin.apt:
      name: "{{ ['language-pack-de', 'language-pack-gnome-de'] if ansible_facts['distribution'] == 'Ubuntu' else ['task-german', 'task-german-desktop'] }}"
      state: latest
      update_cache: yes

  ###########################################################################
  # 4. Anwendungen aus Debian-/Ubuntu-Repositories
  ###########################################################################

  - name: Installiere Standardanwendungen
    ansible.builtin.apt:
      name:
        - chromium-browser
        - chromium-l10n
        - arduino
        - emacs
        - gedit
        - gimp
        - gwenview
        - kate
        - x11vnc
        - gnome-connections
        - shotcut
        - thonny
        - python-is-python3
        - python3-keras-applications
        - python3-keras-preprocessing
        - python3-psutil
        - python3-numpy
        - python3-pygame
        - python3-matplotlib
        - python3-pip
        - python3-venv
        - inkscape
        - catfish
        - flatpak
        - gnome-software-plugin-flatpak
        - gnome-tweaks
        - libreoffice
        - libreoffice-l10n-de
      state: latest
      update_cache: yes
    ignore_errors: yes  # Manche Pakete heißen unter Ubuntu anders

  - name: Falls Chromium nicht im Repo vorhanden ist, installiere über Snap (Ubuntu)
    community.general.snap:
      name: chromium
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'

  ###########################################################################
  # 5. Entferne unerwünschte Spiele
  ###########################################################################

  - name: Deinstalliere Spiele aus dem Repository
    ansible.builtin.apt:
      name:
        - aisleriot
        - 2048
        - iagno
        - robots
        - mahjongg
        - mines
        - sudoku
        - five-or-more
        - hitori
        - four-in-a-row
        - klotski
        - lightsoff
        - nibbles
        - quadrapassel
        - swell-foop
        - tetravex
        - taquin
        - tali
        - gnome-aisleriot
        - gnome-2048
        - gnome-lightsoff
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - gnome-five-or-more
        - gnome-hitori
        - gnome-four-in-a-row
        - gnome-klotski
        - gnome-nibbles
        - gnome-quadrapassel
        - gnome-iagno
        - gnome-robots
        - gnome-swell-foop
        - gnome-tetravex
        - gnome-taquin
        - gnome-tali
      state: absent
    ignore_errors: yes  # falls manche Spiele nicht existieren

  ###########################################################################
  # 6. Flatpak-Integration und Software
  ###########################################################################

  - name: Stelle sicher, dass Flatpak installiert ist
    ansible.builtin.apt:
      name: flatpak
      state: present

  - name: Füge das Flathub Flatpak Repository hinzu
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Installiere Anwendungen aus dem Flathub-Repository
    community.general.flatpak:
      name:
        - ch.tigerjython.TigerJython2
        - de.lernsoftware_filius.Filius
        - org.eclipse.Java
        - org.processing.processingide
        - com.prusa3d.PrusaSlicer
        - com.visualstudio.code
        - edu.mit.Scratch
        - com.github.PintaProject.Pinta
        - cc.arduino.IDE2
        - org.bluej.BlueJ
        - com.jetbrains.IntelliJ-IDEA-Community
        - com.vscodium.codium
        - io.github.pemsley.coot
        - org.localsend.localsend_app
        - org.greenfoot.Greenfoot
        - com.bambulab.BambuStudio
        - org.apache.netbeans
      state: present
      method: system

  ###########################################################################
  # 7. Systempflege
  ###########################################################################

  - name: Entferne nicht mehr benötigte Pakete
    ansible.builtin.apt:
      autoremove: yes
