---
# Dieses Skript enthält die Software-Grundausstattung der PC-Räume, soweit sie über Debian oder Flatpak verfügbar ist. Es erzeugt zudem einen Cronjob,
# der dieses Script alle 10 Minuten neu über Github aufruft. Nach erstmaliger Ausführung des Skriptes über ssh ist also keine weitere manuelle Ausführung 
# erforderlich, da Änderungen am Skript auf Github bei Nutzung der Rechner automatisch nach 10 Minuten von den Clients übernommen werden. Ein Schlüssel
# ist nicht erforderlich, da das Playbook öffentlich im Netz steht. Das Installieren, Aktualisieren oder auch Löschen von Software kann so einmalig im 
# Playbook informatik.yml vorgenommen werden und wird dann automatisch auf alle Clients ausgerollt. Diese Vorgänge finden im Hintergrund statt 
# und stören die Arbeit an den Clients in der Regel nicht.

- hosts: localhost
  connection: local
  become: true
  
#  environment: 
#    http_proxy: http://hg-gym.de/proxy.pac

  tasks:

  - name: Ermittle Daten über das Betriebssystem
    ansible.builtin.debug:
      var: ansible_facts

  - name: Installiere die Sprachpakete des Systems und des Desktops
    package:
      name: 
        - task-german 
        - task-german-desktop
      state: latest
      update_cache: yes

  - name: Installiere den Chromium-Browser und andere distributionsspezifische Pakete in Debian.
    package:
      name:
        - chromium                                # Chromium-Browser, benötigt für LEGO Spike web App etc.
        - chromium-l10n                           # Chromium-Sprachlokalisation
      state: latest
    when: ansible_facts['distribution'] == "Debian"


  - name: Installiere den Chromium-Browser und andere distributionsspezifische Pakete in Ubuntu.
    package:
      name:
        - chromium-browser                        # Chromium-Browser, benötigt für LEGO Spike web App etc.
        - chromium-browser-l10n                   # Chromium-Sprachlokalisation
        - language-pack-de                        # deutsches Sprachpaket für Ubuntu
      state: latest
    when: ansible_facts['distribution'] == "Ubuntu"


  - name: Installiere allgemeine Anwendungen aus dem Debian-Repository
    package:
      name: 
        - arduino                               # Arduino 1
        - emacs                                 # Emacs
        - gedit                                 # GNOME-Editor
        - kate                                  # KDE Editor
#        - veyon-configurator                    # aktuellere Version erforderlich
#        - veyon-plugins
#        - veyon-service
        - x11vnc                                # VNC-Server für X11
        - gnome-connections                     # RDP / VNC-Verbindung
        - shotcut                               # einfaches Videoschnitt-Programm
        - thonny                                # Python für Einsteiger
        - python-is-python3                     # Python  
#        - python3-keras                         # ... sowie weitere Python-Module
        - python3-keras-applications
        - python3-keras-preprocessing
        - python3-psutil                       
        - python3-numpy                       
        - python3-pygame
        - python3-matplotlib
        - python3-pip
        - python3-venv
#        - libtensorflow-cc2
#        - libtensorflow-dev
#        - libtensorflow-framework2
        - inkscape                              # Vektorgrafik
        - catfish                               # Datei- und Volltextsuche
        - flatpak                               # Flatpak 
        - gnome-software-plugin-flatpak         # Integration von Flatpak in GNOME
        - gnome-tweaks                          # GNOME-Optimierungen
        - libreoffice
        - libreoffice-l10n-de
      state: latest

  - name: Deinstalliere Spiele aus dem Debian-Repository
    package:
      name: 
        - aisleriot
        - 2048
        - iagno
        - robots
        - mahjongg
        - mines
        - sudoku
        - five-or-more
        - hitori
        - four-in-a-row
        - klotski
        - lightsoff 
        - nibbles
        - quadrapassel
        - swell-foop
        - tetravex
        - taquin
        - tali
        - gnome-aisleriot
        - gnome-2048
        - gnome-lightsoff
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - gnome-five-or-more
        - gnome-hitori
        - gnome-four-in-a-row
        - gnome-klotski 
        - gnome-nibbles
        - gnome-quadrapassel
        - gnome-iagno
        - gnome-robots
        - gnome-swell-foop
        - gnome-tetravex
        - gnome-taquin
        - gnome-tali
      state: absent

  - name: Füge das Flathub Flatpak Repository zur System-Installation hinzu
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Installiere Anwendungen aus dem Flathub-Repository
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2            # TigerJython Programmier-Lernumgebung für Python
        - de.lernsoftware_filius.Filius          # Filius Netwerkbau
        - org.eclipse.Java                       # Eclipse Java-Editor
        - org.processing.processingide           # Processing Java-Editor 
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Microsoft Visual Studio
        - edu.mit.Scratch                        # Scratch 3 (deb-Paket ist veraltet)
        - com.github.PintaProject.Pinta          # Pendant zu Paint in der Windows-Welt
        - cc.arduino.IDE2                        # Arduino 2
        - org.bluej.BlueJ                        # Java-Editor
        - com.jetbrains.IntelliJ-IDEA-Community  # Java und Kotlin-Editor
        - com.vscodium.codium                    # Java und Visual Studio Editor
        - io.github.pemsley.coot                 # Makromoleküle bauen
        - org.localsend.localsend_app            # plattformübergreifendes Airdropping
      state: present

  - name: Stelle sicher, dass der Cronjob-Daemon läuft
    ansible.builtin.systemd_service:
      state: started
      name: cron
      daemon_reload: true
      enabled: true

  - name: Füge den Ansible-pull Cronjob hinzu
    ansible.builtin.cron: 
      name: ansible auto-provision
      user: root
      minute: "*/10"
      hour: "*"
      day: "*"
      job: sudo ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git informatik.yml
 
  - name: Entferne überflüssigen Nutzer 'velociraptor'
    ansible.builtin.user:
      name: velociraptor
      state: absent
      remove: yes

  - name: Deinstalliere die alte Veyon-Version aus dem Debian-Repository
    package:
      name: 
        - libveyon-core
        - veyon-configurator
        - veyon-master
        - veyon-plugins
        - veyon-service
      state: absent

  - name: Prüfe, welche Pakete vorhanden sind
    package_facts:
      manager: apt

  - name: Erzeuge das Verzeichnis packages, falls es noch nicht existiert
    ansible.builtin.file:
      path: /home/administrator/packages
      state: directory
      mode: '0755'

  - name: Kopiere die Installationsdatei von Veyon in ein lokales Verzeichnis des Administrators
    ansible.builtin.get_url:
      url: https://github.com/veyon/veyon/releases/download/v4.9.3/veyon_4.9.3.0-debian.12_amd64.deb
      dest: /home/administrator/packages/veyon_4.9.3.0-debian.12_amd64.deb
      mode: '0644'
#    when: '"veyon" not in ansible_facts.packages'

  - name: Installiere die aktuelle Version des Programms Veyon
    ansible.builtin.apt:
      deb: /home/administrator/packages/veyon_4.9.3.0-debian.12_amd64.deb
      state: present
#    when: '"veyon" not in ansible_facts.packages'

  - name: Entferne die Installationsdatei von Veyon
    ansible.builtin.file:
      path: /home/administrator/packages/veyon_4.9.3.0-debian.12_amd64.deb
      state: absent

  - name: Lade Veyon Konfigurationsdatei herunter
    get_url:
      url: https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyon-settings-HG-Linux.json
      dest: /tmp/veyon-settings-HG-Linux.json
      mode: '0644'

  - name: Lade Veyon Netzwerkobjekte CSV herunter
    get_url:
      url: https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/raum311-import-file.csv
      dest: /tmp/raum311-import-file.csv
      mode: '0644'

  - name: Importiere Veyon Konfigurationsdatei
    command: sudo veyon-cli config import /tmp/veyon-settings-HG-Linux.json
 
#  - name: Importiere Veyon Netzwerkobjekte
#    command: sudo veyon-cli networkobjects import /tmp/raum311-import-file.csv format "%location%,%name%,%host%,%mac%"

  - name: Download Veyon public key
       ansible.builtin.get_url:
         url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/PC-Raum311_public_key.pem"
         dest: "/tmp/PC-Raum311_public_key.pem"
         mode: '0644'

  - name: Import the Veyon public key
    ansible.builtin.command:
      cmd: "veyon-cli authkeys import /tmp/PC-Raum311_public_key.pem"
    register: veyon_import_result
    changed_when: veyon_import_result.rc == 0

  - name: Remove the temporary key file
    ansible.builtin.file:
      path: "/tmp/PC-Raum311_public_key.pem"
      state: absent
