---
- hosts: localhost
  connection: local
  become: true
  vars: 
    flatpakrepo: https://dl.flathub.org/repo/flathub.flatpakrepo/appstream/

  tasks:
  - name: Installiere Debian-Pakete
    package:
      name: 
        - arduino              # Arduino 1
        - emacs                # Emacs
        - gedit                # GNOME-Editor
        - kate                 # KDE Editor
        - veyon-configurator   # Veyon für Schülergeräte
        - chromium             # Chromium-Browser, benötigt für LEGO Spike web App etc.
        - shotcut              # einfaches Videoschnitt-Programm
        - python-is-python3    # Python  
        - inkscape             # Vektorgrafik
        - python3-psutil

  - name: Installiere Flatpak-Pakete
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2            # TigerJython Programmier-Lernumgebung für Python
        - de.lernsoftware_filius.Filius          # Flius Netwerkbau
        - org.eclipse.Java                       # Eclipse Java-Editor
        - org.processing.processingide           # Processing Java-Editor 
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Microsoft Visual Studio
        - edu.mit.Scratch                        # Scratch 3 (deb-Paket ist veraltet)
        - com.github.PintaProject.Pinta          # Pendant zu Paint in der Windows-Welt
        - cc.arduino.IDE2                        # Arduino 2
      state: present

  - name: Synchronisiere die Hersteller-Pakete in ein lokales Verzeichnis
    ansible.posix.synchronize:
      src: /home/holger/dev/ansible-packages/
      dest: /home/holger/packages/
#      job: "./Structorizer.sh -D ~/packages/Structorizer"


