---
- hosts: localhost
  connection: local
  become: true
  vars: 
    flatpakrepo: https://dl.flathub.org/repo/flathub.flatpakrepo/appstream/

  tasks:
  - name: Installiere Debian-Pakete
    package:
      name: 
        - arduino              # Arduino 1
        - emacs                # Emacs
        - gedit                # GNOME-Editor
        - kate                 # KDE Editor
        - veyon-configurator   # Veyon für Schülergeräte
        - chromium             # Chromium-Browser
        - shotcut              # einfaches Videoschnitt-Programm
        - python-is-python3    # Python  
        - inkscape             # Vektorgrafik
        - python3-psutil

  - name: Installiere Flatpak-Pakete
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2
        - de.lernsoftware_filius.Filius
        - org.eclipse.Java
        - org.processing.processingide
        - com.prusa3d.PrusaSlicer
        - com.visualstudio.code
        - edu.mit.Scratch
        - com.github.PintaProject.Pinta
        - cc.arduino.IDE2
      state: present

  - name: Kopiere die Hersteller-Pakete in ein Verzeichnis
    copy:
      src: ~/ansible-desktop/packages/
      dest: ~/packages/
     

#  - name: Einen Ansible-User hinzufuegen
#    user: 
#      name: tueroeffner
#      system: yes

#  - name: Ansible-Nutzer zur Sudo-Gruppe hinzufuegen
#    copy: 
#      src: files/sudoer_tueroeffner
#      dest: /etc/sudoers.d/tueroeffner
#      owner: root
#      group: root
#      mode: 0440

#  - name: Ansible-pull Cronjob hinzufuegen
#    cron: 
#      - name: ansible auto-provision
#      - user: tueroeffner
#      - minute: "*/10"
#      - job: sudo ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git
 

