---
# Dieses Playbook installiert die Software-Grundausstattung der PC-Räume
# für Debian- und Ubuntu-Systeme mit Cinnamon-Desktop.
# Es richtet einen Cronjob ein, der das Playbook alle 10 Minuten über GitHub neu ausführt.
# Änderungen am zentralen Playbook werden dadurch automatisch auf allen Clients übernommen.

- hosts: localhost
  connection: local
  become: true

  vars:
    repo_url: "https://github.com/hvoss71/ansible_desktop.git"
    playbook_file: "informatik.yml"

  tasks:

  ###########################################################################
  # 1. Cronjob für automatische Aktualisierung
  ###########################################################################

  - name: Stelle sicher, dass der Cron-Dienst aktiv ist
    ansible.builtin.systemd:
      name: cron
      state: started
      enabled: true
      daemon_reload: true

  - name: Füge Cronjob für automatischen ansible-pull hinzu
    ansible.builtin.cron:
      name: "Ansible Auto-Provision"
      user: root
      minute: "*/10"
      job: "ansible-pull -o -U {{ repo_url }} {{ playbook_file }} > /var/log/ansible-pull.log 2>&1"
      state: present

  ###########################################################################
  # 2. Benutzer- und Gruppenverwaltung
  ###########################################################################

  - name: Stelle sicher, dass die Gruppe 'hainberg' existiert
    ansible.builtin.group:
      name: hainberg
      state: present

  - name: Erzeuge lokalen Notfall-Benutzer 'hainberg-local'
    ansible.builtin.user:
      name: hainberg-local
      uid: 2001
      group: users
      create_home: yes
      shell: /bin/bash
      password: "{{ 'hainberg' | password_hash('sha512') }}"
      state: present

  ###########################################################################
  # 3. System- und Sprachpakete
  ###########################################################################

  - name: Aktualisiere Paketquellen und installiere Systemupdates
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      
  - name: Installiere System- und Desktop-Sprachpakete (Deutsch)
    ansible.builtin.apt:
      name: "{{ (['task-german'] if ansible_facts['distribution'] == 'Debian' else ['language-pack-de', 'language-pack-gnome-de']) + ['cinnamon-translations'] }}"
      state: latest
      update_cache: yes



  ###########################################################################
  # 4. Anwendungen aus Debian-/Ubuntu-Repositories
  ###########################################################################

  - name: Installiere Standardanwendungen
    ansible.builtin.apt:
      name:
        # --- Browser ---
        - chromium-browser
        - chromium-l10n

        # --- Entwicklung / Informatik ---
        - arduino
        - emacs
        - thonny
        - python-is-python3
        - python3-keras-applications
        - python3-keras-preprocessing
        - python3-psutil
        - python3-numpy
        - python3-pygame
        - python3-matplotlib
        - python3-pip
        - python3-venv

        # --- Grafik / Multimedia ---
        - gimp
        - gwenview
        - inkscape
        - shotcut

        # --- Büro / Unterricht ---
        - libreoffice
        - libreoffice-l10n-de

        # --- Netzwerk / Fernzugriff ---
        - x11vnc
        - remmina

        # --- Cinnamon Desktop ---
        - cinnamon
        - cinnamon-common
        - nemo-fileroller
        - nemo-share
        - xed
        - catfish
        - flatpak
        - mintinstall

      state: latest
      update_cache: yes
    ignore_errors: yes

  ###########################################################################
  # 5. Entferne unerwünschte Spiele
  ###########################################################################

  - name: Entferne überflüssige GNOME-Spiele
    ansible.builtin.apt:
      name:
        - aisleriot
        - 2048
        - iagno
        - robots
        - mahjongg
        - mines
        - sudoku
        - five-or-more
        - hitori
        - four-in-a-row
        - klotski
        - lightsoff
        - nibbles
        - quadrapassel
        - swell-foop
        - tetravex
        - taquin
        - tali
      state: absent
    ignore_errors: yes

  ###########################################################################
  # 6. Flatpak-Integration und externe Software
  ###########################################################################

  - name: Stelle sicher, dass Flatpak installiert ist
    ansible.builtin.apt:
      name: flatpak
      state: present

  - name: Füge Flathub-Repository hinzu
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
      method: system

  - name: Installiere Unterrichtssoftware über Flatpak
    community.general.flatpak:
      name:
        - ch.tigerjython.TigerJython2
        - de.lernsoftware_filius.Filius
        - org.eclipse.Java
        - org.processing.processingide
        - com.prusa3d.PrusaSlicer
        - com.visualstudio.code
        - edu.mit.Scratch
        - com.github.PintaProject.Pinta
        - cc.arduino.IDE2
        - org.bluej.BlueJ
        - com.jetbrains.IntelliJ-IDEA-Community
        - com.vscodium.codium
        - org.greenfoot.Greenfoot
        - com.bambulab.BambuStudio
        - org.apache.netbeans
      state: present
      method: system

  ###########################################################################
  # 7. Systempflege
  ###########################################################################

  - name: Entferne nicht mehr benötigte Pakete
    ansible.builtin.apt:
      autoremove: yes
      autoclean: yes


  - name: Ausgabe nach erfolgreicher Installation
    ansible.builtin.debug:
      msg: >
        Informatik-Grundausstattung (Cinnamon) wurde installiert.
        Das System prüft alle 10 Minuten auf Aktualisierungen über GitHub.
        Ein Neustart ist empfehlenswert, um Sprach- und Desktopkomponenten zu aktivieren.
