---
- hosts: localhost
  connection: local
  become: true
#  vars: 
#    flatpakrepo: https://dl.flathub.org/repo/flathub.flatpakrepo/appstream/

  tasks:
  - name: Installiere Pakete aus dem Debian-Repository
    package:
      name: 
        - arduino                               # Arduino 1
        - emacs                                 # Emacs
        - gedit                                 # GNOME-Editor
        - kate                                  # KDE Editor
        - veyon-configurator                    # Veyon für Schülergeräte
        - chromium                              # Chromium-Browser, benötigt für LEGO Spike web App etc.
        - shotcut                               # einfaches Videoschnitt-Programm
        - python-is-python3                     # Python  
        - python3-psutil                        # Abrufen von Informationen über laufende Prozesse
        - inkscape                              # Vektorgrafik
        - catfish                               # Datei- und Volltextsuche
#        - filius                                # Filius Rechnernetzwerke - Paket wurde entfernt

#  - name: Installiere die Hersteller-Pakete
#    ansible.builtin.apt:
#      deb: /home/administrator/packages/MindPlus/MindPlus_1.7.3-202307011900_amd64_x86.deb
#      deb: /home/administrator/packages/Structorizer/structorizer_3.32-19.deb
#      deb: 


#  -  name: Add the flathub flatpak repository remote to the user installation
#     community.general.flatpak_remote:
#       name: flathub
#       state: present
#       flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
#       method: user

#  - name: Add the Gnome flatpak remote to the system installation
#    community.general.flatpak_remote:
#      name: gnome
#      state: present
#      flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

  - name: Installiere Flatpak
    package:
      name:
        - flatpak                               # Flatpak + GNOME Software-Plugin
        - gnome-software-plugin-flatpak
#      deb: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Installiere Flatpak-Pakete
    community.general.flatpak:
      name:  
        - ch.tigerjython.TigerJython2            # TigerJython Programmier-Lernumgebung für Python
        - de.lernsoftware_filius.Filius          # Filius Netwerkbau
        - org.eclipse.Java                       # Eclipse Java-Editor
        - org.processing.processingide           # Processing Java-Editor 
        - com.prusa3d.PrusaSlicer                # 3D-Druck
        - com.visualstudio.code                  # Microsoft Visual Studio
        - edu.mit.Scratch                        # Scratch 3 (deb-Paket ist veraltet)
        - com.github.PintaProject.Pinta          # Pendant zu Paint in der Windows-Welt
        - cc.arduino.IDE2                        # Arduino 2
        - org.bluej.BlueJ                        # Java-Editor
        - com.jetbrains.IntelliJ-IDEA-Community  # Java und Kotlin-Editor
        - com.vscodium.codium                    # Java und visual Studio Editor
      state: present

  - name: Ansible-pull Cronjob hinzufügen
    cron: 
      - name: ansible auto-provision
      - user: administrator
      - minute: "*/10"
      - job: sudo ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git informatik.yml
 
