---
# Einrichtung des Klausurprofils inkl. Nutzer und Prüfungssoftware

- hosts: Raum311
  connection: ssh
  become: true

  tasks:
  - name: Erzeuge eine Gruppe "Klausur"
    ansible.builtin.group:
      name: klausur
      gid: 1010
      state: present

  - name: Erzeuge einen Nutzer 'Klausur' mit einem eigenen Home-Verzeichnis
    ansible.builtin.user:
      name: klausur
      comment: Klausur
      group: klausur
      state: present
      uid: 1010
      create_home: yes
      state: present
#      password: 'klausur'
#      update_password: always 

  - name: Initiale Passwort-Erzeugung für den Nutzer klausur
    shell: usermod -p $(echo 'klausur' | openssl passwd -1 -stdin) 'klausur'

# Das Passwort kann aufgrund neuer Sicherheitsbestimmungen nicht mehr direkt 
# gesetzt werden. Im der hier verwendeten Shell-Anweisung wird das Passwort
# bei jedem Aufruf des Playbooks neu (zurück-)gesetzt.

  - name: Kopiere die Prüfungssoftware auf den Desktop des Klausuraccounts
    ansible.builtin.copy:
      src: /home/softwareverteilung/dev/ansible-packages/Next-Exam/Next-Exam-Student_1.0.0.AppImage
      dest: /home/klausur/Arbeitsfläche/
      owner: klausur
      group: klausur
      mode: 0540   # - r-x r-- ---

# Die Prüfungssoftware wird schreibgeschützt, ist aber lokal ausführbar.
