---
# Einrichtung des Klausurprofils inkl. Nutzer und Software
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Erzeuge eine Gruppe "Klausur"
    ansible.builtin.group:
      name: klausur
      gid: 1010
      state: present

  - name: Erzeuge einen Nutzer 'Klausur' mit einem eigenen Home-Verzeichnis
    ansible.builtin.user:
      name: klausur
      comment: Klausur
      group: klausur
      state: present
      uid: 1010
      create_home: yes
      state: present
      password: "'klausur'"
      update_password: always

#  - name: Initial password generation for user 'klausur'
#    shell: usermod -p $(echo 'klausur' | openssl passwd -1 -stdin) 'klausur'
    

  - name: Kopiere die Prüfungssoftware auf den Desktop des Klausuraccounts
    ansible.builtin.copy:
      src: /home/holger/dev/ansible-packages/Next-Exam/Next-Exam-Student_1.0.0.AppImage
      dest: /home/klausur/Arbeitsfläche/
      owner: klausur
      group: klausur
