---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: installiere Debian-Pakete
    package:
      name: 
        - arduino
        - emacs
        - gedit
        - kate
        - veyon-configurator
        - shotcut
        - python-is-python3
        - inkscape
        - python3-psutil

  - name: Kopiere .bashrc-Datei
    copy:
      src: files/bashrc
      dest: /home/holger/.bashrc
      owner: holger
      group: holger

  - name: Einen Ansible-User hinzufügen
    user: 
      name: tueroeffner
      system: yes

  - name: Ansible-Nutzer zur Sudo-Gruppe hinzufügen
    copy: 
      src: files/sudoer_tueroeffner
      dest: etc/sudoers.d/tueroeffner
      owner: root
      group: root
      mode: 0440

  - name: Ansible-pull Cronjob hinzufügen
    cron: 
      - name: ansible auto-provision
      - user: tueroeffner
      - minute: "*/10"
      - job: sudo ansible-pull -o -U https://github.com/hvoss71/ansible_desktop.git
 

