---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: installiere Debian-Pakete
    package:
      name: 
        - arduino
        - emacs
        - gedit
        - kate
        - veyon-configurator
        - shotcut
        - python-is-python3
        - inkscape
        - python3-psutil

  - name: Kopiere .bashrc-Datei
    copy:
      src: files/bashrc
      dest: /home/holger/.bashrc
      owner: holger
      group: holger

