---
- name: Setze Proxy-Server für Benutzer administrator
  hosts: debian
  become: yes
  tasks:
    - name: Erstelle die Konfigurationsdatei für den Proxy-Server
      copy:
        dest: "/home/administrator/.bashrc"
        content: |
          # Proxy-Einstellungen für administrator
          export http_proxy="http://hg-gym.de/proxy.pac"
          export https_proxy="http://hg-gym.de/proxy.pac"
          export ftp_proxy="http://hg-gym.de/proxy.pac"
          export no_proxy="localhost,127.0.0.1,*.hg-gym.de"
        owner: administrator
        group: administrator
        mode: '0644'

    - name: Setze Proxy-Einstellungen für apt
      blockinfile:
        path: /etc/apt/apt.conf.d/95proxies
        block: |
          Acquire::http::Proxy "http://hg-gym.de/proxy.pac";
          Acquire::https::Proxy "http://hg-gym.de/proxy.pac";
          Acquire::ftp::Proxy "http://hg-gym.de/proxy.pac";

    - name: Setze Proxy-Einstellungen für das System
      lineinfile:
        path: /etc/environment
        regexp: '^http_proxy'
        line: 'http_proxy="http://hg-gym.de/proxy.pac"'

  handlers:
    - name: Neustart der Dienste
      service:
        name: networking
        state: restarted
