---
- name: Setze Proxy für localhost und Benutzer administrator
  hosts: localhost
  become: yes
  tasks:

    # Schritt 1: Erstelle die APT-Konfigurationsdatei für Proxy
    - name: Erstelle eine APT-Konfigurationsdatei für Proxy
      copy:
        dest: "/etc/apt/apt.conf.d/95proxies"
        content: |
          Acquire::http::Proxy "http://hg-gym.de/proxy.pac";
          Acquire::https::Proxy "http://hg-gym.de/proxy.pac";
          Acquire::ftp::Proxy "http://hg-gym.de/proxy.pac";
          Acquire::http::No-Cache "true";  # optional, je nach Bedarf
      when: not ansible_facts['distribution'] == 'Debian'

    # Schritt 2: Setze Proxy für den Benutzer administrator
    - name: Erstelle Proxy-Umgebungsvariablen für administrator
      lineinfile:
        path: "/home/administrator/.bashrc"
        regexp: '^export {{ item.name }}='
        line: "export {{ item.name }}={{ item.value }}"
      loop:
        - { name: 'http_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'https_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'ftp_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'no_proxy', value: 'localhost,127.0.0.1' }
      become_user: administrator

    # Schritt 3: Setze den Proxy in der Systemumgebung (für alle Benutzer)
    - name: Setze Proxy in der Systemumgebung
      lineinfile:
        path: "/etc/environment"
        regexp: '^{{ item.name }}='
        line: "{{ item.name }}={{ item.value }}"
      loop:
        - { name: 'http_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'https_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'ftp_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'no_proxy', value: 'localhost,127.0.0.1' }

    # Schritt 4: Bestätige, dass der Proxy korrekt gesetzt ist (für administrator)
    - name: Bestätige, dass der Proxy korrekt gesetzt ist
      command: echo $http_proxy
      become_user: administrator
      register: result

    # Schritt 5: Zeige den Proxy-Wert an
    - name: Zeige den Proxy-Wert an
      debug:
        var: result.stdout
