---
- name: Setze Proxy f체r Benutzer administrator auf Debian
  hosts: all
  become: yes
  tasks:

    - name: Erstelle die Proxy-Umgebungsvariablen f체r administrator
      lineinfile:
        path: "/home/administrator/.bashrc"
        regexp: '^export {{ item.name }}='
        line: "export {{ item.name }}={{ item.value }}"
      loop:
        - { name: 'http_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'https_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'ftp_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'no_proxy', value: 'localhost,127.0.0.1' }
      become_user: administrator

    - name: Setze den Proxy in der Systemumgebung (f체r alle Benutzer)
      lineinfile:
        path: "/etc/environment"
        regexp: '^{{ item.name }}='
        line: "{{ item.name }}={{ item.value }}"
      loop:
        - { name: 'http_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'https_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'ftp_proxy', value: 'http://hg-gym.de/proxy.pac' }
        - { name: 'no_proxy', value: 'localhost,127.0.0.1' }

    - name: Aktualisiere die Umgebungsvariablen
      command: source /home/administrator/.bashrc
      become_user: administrator

    - name: Best채tige, dass der Proxy korrekt gesetzt ist
      command: echo $http_proxy
      become_user: administrator
      register: result

    - name: Zeige den Proxy-Wert an
      debug:
        var: result.stdout
