---
# ======================================================================
# Playbook: ssh-key-setup.yml
# Zweck:    Öffentlichen SSH-Schlüssel für den Administrator installieren
# ======================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    user_name: "administrator"
    ssh_key_url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/public_keys/hgadmin_ed25519.pub"

  tasks:
    - name: Stelle sicher, dass das .ssh-Verzeichnis des Administrators existiert
      ansible.builtin.file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0700'

    - name: Installiere öffentlichen SSH-Schlüssel für Administrator direkt von GitHub
      ansible.builtin.authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('url', ssh_key_url) }}"
        state: present

    - name: Stelle Berechtigungen für authorized_keys sicher
      ansible.builtin.file:
        path: "/home/{{ user_name }}/.ssh/authorized_keys"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
        state: file
