---
# ======================================================================
# Playbook: start-Raum313.yml
# Zweck:    Initialisierung von Clients im Raum 313
#           - SSH-Key-Setup starten
#           - Veyon-Installer, Raumkonfiguration und Basissoftware ausrollen
# ======================================================================

- hosts: localhost
  connection: local
  become: true
  
  vars:
    room: "Raum313"

  vars:
    repo_url: "https://github.com/hvoss71/ansible_desktop.git"
    playbooks:
      - "ssh-key-setup.yml"
      - "veyon-installer.yml"
      - "veyon-config-313.yml"
      - "informatik.yml"

  tasks:
    - name: Stelle sicher, dass Git, Python und Ansible installiert sind
      ansible.builtin.apt:
        name:
          - git
          - python3
          - python3-pip
          - ansible
        state: present
        update_cache: yes

    - name: Führe die vorbereiteten Playbooks direkt aus dem GitHub-Repository aus
      ansible.builtin.command:
        cmd: "ansible-pull -o -U {{ repo_url }} {{ item }}"
      loop: "{{ playbooks }}"
      register: pull_results
      changed_when: "'changed' in (pull_results.stdout | lower) or 'changed' in (pull_results.stderr | lower)"
