---
# Dieses Playbook installiert das Programm Structorizer. Das Debian-Paket des Herstellers 
# ist weder 端ber die Debian-Repositories noch 端ber Flathub verf端gbar und kann daher nur 
# direkt beim Hersteller (端ber Github) bezogen werden.

- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Kopiere die Installationsdatei in ein lokales Verzeichnis des Administrators
    ansible.builtin.get_url:
#      url:  http://public.dzogovic.org/structorizer_3.23.deb
      url: https://github.com/fesch/Structorizer.Desktop/releases/download/3.32-25/structorizer.deb
#      url: https://www.fisch.lu/Php/download.php?file=structorizer.deb
      dest: /home/administrator/packages/structorizer.deb
      mode: '0644'

  - name: Installiere das Programm
    ansible.builtin.apt:
#      deb: /home/administrator/packages/MindPlus/MindPlus_1.7.3-202307011900_amd64_x86.deb
      deb: /home/administrator/packages/structorizer.deb

  - name: Entferne die Installationsdatei
    ansible.builtin.file:
      path: /home/administrator/packages/structorizer.deb
      state: absent
