- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_path: "/usr/bin/uxplay"
    room_name: "Raum 123"

  tasks:

    - name: Stelle sicher, dass Autostart-Verzeichnis existiert
      file:
        path: /etc/xdg/autostart
        state: directory
        mode: "0755"

    - name: Erstelle systemweiten Autostart für uxplay
      copy:
        dest: /etc/xdg/autostart/uxplay.desktop
        owner: root
        group: root
        mode: "0644"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver
          Comment=Startet uxplay automatisch
          Exec={{ uxplay_path }} -n {{ room_name }} -nh
          Icon=display
          Terminal=false
          X-GNOME-Autostart-enabled=true
