---
# ======================================================================
# Playbook: uxplay-desktop-button.yml
# Zweck:    Erstellt Desktopstarter für uxplay (AirPlay Receiver)
#           für alle echten Benutzer mit /home/* (UID >= 1000)
# ======================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_icon: "/usr/share/icons/hicolor/128x128/apps/uxplay.png"

  tasks:

    # --------------------------------------------------------------
    # 1. Lese alle Benutzerzeilen aus /etc/passwd
    # --------------------------------------------------------------
    - name: Lese alle Benutzer aus /etc/passwd
      command: getent passwd
      register: passwd_entries
      changed_when: false

    # --------------------------------------------------------------
    # 2. Extrahiere nur echte Benutzer (UID >= 1000, /home/*)
    # --------------------------------------------------------------
    - name: Erzeuge Liste der realen Benutzer
      set_fact:
        ansible_users: "{{ ansible_users | default([]) + [ {'name': fields[0], 'home': fields[5]} ] }}"
      vars:
        fields: "{{ item.split(':') }}"
      loop: "{{ passwd_entries.stdout_lines }}"
      when:
        - fields[2] | int >= 1000
        - fields[0] != 'nobody'
        - fields[5] is match('^/home/')

    - name: Zeige gefundene Benutzer
      debug:
        var: ansible_users

    # --------------------------------------------------------------
    # 3. Stelle sicher, dass Desktop-Verzeichnisse existieren
    # --------------------------------------------------------------
    - name: Stelle sicher, dass Desktop-Verzeichnisse existieren
      file:
        path: "{{ item.home }}/Desktop"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    # --------------------------------------------------------------
    # 4. Desktopstarter anlegen (im Terminal)
    # --------------------------------------------------------------
    - name: Erstelle uxplay-Starter auf dem Desktop
      copy:
        dest: "{{ item.home }}/Desktop/uxplay-terminal.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- /usr/bin/uxplay -n {{ ansible_hostname }} -nh
          Icon={{ uxplay_icon }}
          Terminal=false
          StartupNotify=true
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    # --------------------------------------------------------------
    # 5. Ausgabe
    # --------------------------------------------------------------
    - name: Erfolgsmeldung
      debug:
        msg: "Desktopstarter für uxplay wurde auf allen Benutzer-Desktops erstellt."
