---
# ================================================================
# Playbook: uxplay-desktop-terminal.yml
# Zweck:    Desktop-Button f端r Cinnamon erstellen, um uxplay
#           manuell im Terminal zu starten, f端r alle Benutzer
# ================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_path: "/usr/bin/uxplay"
    room_name: "{{ ansible_hostname }}"
    uxplay_icon: "/usr/share/icons/hicolor/128x128/apps/uxplay.png"

  tasks:

    - name: Sammle alle normalen Benutzer (UID >= 1000, kein nobody)
      ansible.builtin.set_fact:
        ansible_users: "{{ ansible_users | default([]) + [ {'name': item.split(':')[0], 'home': item.split(':')[5]} ] }}"
      loop: "{{ lookup('ansible.builtin.pipe','getent passwd', wantlist=True) }}"
      when: (item.split(':')[2]|int) >= 1000 and item.split(':')[0] != 'nobody'

    - name: Stelle sicher, dass Desktop-Verzeichnisse existieren
      file:
        path: "{{ item.home }}/Desktop"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    - name: Desktop-Button f端r uxplay im Terminal anlegen (bestehende Benutzer)
      copy:
        dest: "{{ item.home }}/Desktop/uxplay-terminal.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- {{ uxplay_path }} -n {{ room_name }} -nh
          Icon={{ uxplay_icon }}
          Terminal=false
          StartupNotify=true
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    - name: Desktop-Button f端r neue Benutzer vorbereiten (/etc/skel)
      copy:
        dest: "/etc/skel/Desktop/uxplay-terminal.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- {{ uxplay_path }} -n {{ room_name }} -nh
          Icon={{ uxplay_icon }}
          Terminal=false
          StartupNotify=true
        owner: root
        group: root
        mode: "0755"
