---
- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_path: "/usr/bin/uxplay"
    room_name: "{{ ansible_hostname }}"

  tasks:

  - name: Desktop-Button für uxplay im Terminal auf Cinnamon-Clients
    copy:
      dest: "/home/{{ item }}/Desktop/uxplay-terminal.desktop"
      content: |
       [Desktop Entry]
       Type=Application
       Name=AirPlay Receiver (Terminal)
       Comment=Starte uxplay im Terminal
       Exec=gnome-terminal -- /usr/bin/uxplay -n {{ ansible_hostname }} -nh
       Icon=/usr/share/icons/hicolor/128x128/apps/uxplay.png
       Terminal=false
       StartupNotify=true
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: "0755"
    loop: "{{ lookup('ansible.builtin.pipe','getent passwd | cut -d: -f1 | grep -v nobody', wantlist=True) }}"
