---
# ======================================================================
# Playbook: uxplay-user-service.yml
# Zweck:    Startet uxplay automatisch für alle Nutzer (lokal oder Kerberos)
#           mit raum-/geräteabhängigem Namen, im Benutzerkontext.
# ======================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    # Wird im AirPlay-Menü angezeigt (z. B. Raumname oder Gerätename)
    room_name: "{{ ansible_hostname }}"
    uxplay_path: "/usr/bin/uxplay"

  tasks:

  - name: Entferne systemweiten uxplay-Dienst, falls vorhanden
    ansible.builtin.file:
      path: /etc/systemd/system/uxplay.service
      state: absent

  - name: Stelle sicher, dass systemd-user-Verzeichnis existiert
    ansible.builtin.file:
      path: /etc/systemd/user
      state: directory
      owner: root
      group: root
      mode: "0755"

  - name: Installiere uxplay user service
    ansible.builtin.copy:
      dest: /etc/systemd/user/uxplay.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=AirPlay Receiver (uxplay) - Benutzerkontext
        After=graphical-session.target

        [Service]
        Type=simple
        ExecStart={{ uxplay_path }} -n {{ room_name }} -nh
        Restart=on-failure

        [Install]
        WantedBy=default.target

  - name: systemd daemon neu laden (systemweit)
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Aktivieren von uxplay für aktuell eingeloggte Nutzer
    ansible.builtin.shell: |
      loginctl list-users --no-legend | awk '{print $1}' | while read uid; do
        username=$(getent passwd $uid | cut -d: -f1)
        if [ -n "$username" ]; then
          echo "Aktiviere uxplay für Benutzer: $username"
          sudo -u "$username" bash -c "systemctl --user daemon-reload; systemctl --user enable --now uxplay.service || true"
        fi
      done
    args:
      executable: /bin/bash
    changed_when: false

  - name: systemd-user-Services bei zukünftigen Logins aktiv machen
    ansible.builtin.copy:
      dest: /etc/skel/.config/systemd/user/default.target.wants/uxplay.service
      src: /etc/systemd/user/uxplay.service
      remote_src: true
      owner: root
      group: root
      mode: "0644"
