---
# ================================================================
# Playbook: uxplay-user-service.yml
# Zweck:    AirPlay-Empfänger (uxplay) als User-Service für alle
#           bestehenden und neuen Nutzer einrichten.
#           Funktioniert auf Debian 12 / Ubuntu.
# ================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    room_name: "{{ ansible_hostname }}"   # Name im AirPlay-Menü
    uxplay_path: "/usr/bin/uxplay"

  tasks:

  - name: Entferne systemweiten uxplay-Dienst, falls vorhanden
    ansible.builtin.file:
      path: /etc/systemd/system/uxplay.service
      state: absent

  - name: Stelle sicher, dass /etc/systemd/user existiert
    ansible.builtin.file:
      path: /etc/systemd/user
      state: directory
      owner: root
      group: root
      mode: "0755"

  - name: Installiere uxplay user service
    ansible.builtin.copy:
      dest: /etc/systemd/user/uxplay.service
      owner: root
      group: root
      mode: "0644"
      content: |
        [Unit]
        Description=AirPlay Receiver (uxplay) - Benutzerkontext
        After=graphical-session.target

        [Service]
        Type=simple
        Environment=DISPLAY=:0
        Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/%U/bus
        ExecStart={{ uxplay_path }} -n {{ room_name }} -nh
        Restart=on-failure

        [Install]
        WantedBy=default.target

  - name: Reload systemd system daemon
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Aktiviere uxplay für alle aktuell eingeloggten Nutzer
    ansible.builtin.shell: |
      loginctl list-users --no-legend | awk '{print $1}' | while read uid; do
        user=$(getent passwd $uid | cut -d: -f1)
        if [ -n "$user" ]; then
          echo "Aktiviere uxplay für Benutzer: $user"
          sudo -u "$user" bash -c 'systemctl --user daemon-reload; systemctl --user enable --now uxplay.service || true'
        fi
      done
    args:
      executable: /bin/bash
    changed_when: false

  - name: Stelle sicher, dass Verzeichnisse für neue Nutzer existieren
    ansible.builtin.file:
      path: /etc/skel/.config/systemd/user/default.target.wants
      state: directory
      mode: "0755"

  - name: Kopiere uxplay Unit für zukünftige Nutzer
    ansible.builtin.copy:
      src: /etc/systemd/user/uxplay.service
      dest: /etc/skel/.config/systemd/user/default.target.wants/uxplay.service
      remote_src: true
      owner: root
      group: root
      mode: "0644"
