---
# ======================================================================
# Playbook: uxplay-desktop-button.yml
# Zweck:    Erstellt Desktopstarter für uxplay (AirPlay Receiver)
#           auf deutschsprachigen Cinnamon-Systemen
#           - Terminal-Start
#           - Icon liegt in files/uxplay.png
# ======================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_icon: "/usr/share/icons/hicolor/128x128/apps/uxplay.png"

  tasks:

    # --------------------------------------------------------------
    # 1. Kopiere uxplay-Icon (aus Repository)
    # --------------------------------------------------------------
    - name: Kopiere uxplay-Icon nach Systempfad
      copy:
        src: "files/uxplay.png"
        dest: "{{ uxplay_icon }}"
        mode: "0644"

    # --------------------------------------------------------------
    # 2. Alle Benutzer aus /etc/passwd lesen
    # --------------------------------------------------------------
    - name: Lese alle Benutzer aus /etc/passwd
      command: getent passwd
      register: passwd_entries
      changed_when: false

    # --------------------------------------------------------------
    # 3. Filtere echte Benutzer (UID >= 1000, kein nobody)
    # --------------------------------------------------------------
    - name: Erzeuge Liste der realen Benutzer
      set_fact:
        ansible_users: "{{ ansible_users | default([]) + [ {'name': fields[0], 'home': fields[5]} ] }}"
      vars:
        fields: "{{ item.split(':') }}"
      loop: "{{ passwd_entries.stdout_lines }}"
      when:
        - fields[2] | int >= 1000
        - fields[0] != 'nobody'
        - fields[5] is match('^/home/')

    - name: Zeige gefundene Benutzer
      debug:
        var: ansible_users

    # --------------------------------------------------------------
    # 4. Desktop-Verzeichnisse sicherstellen (deutsche Cinnamon-Variante)
    # --------------------------------------------------------------
    - name: Stelle sicher, dass Verzeichnis Desktop existiert
      file:
        path: "{{ item.home }}/Arbeitsfläche"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    # --------------------------------------------------------------
    # 5. Arbeitsflächestarter anlegen (Terminalstart)
    # --------------------------------------------------------------
    - name: Erstelle uxplay-Starter auf der Desktop
      copy:
        dest: "{{ item.home }}/Arbeitsfläche/uxplay-terminal.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- /usr/bin/uxplay -n {{ ansible_hostname }} -nh
          Icon={{ uxplay_icon }}
          Terminal=false
          StartupNotify=true
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    # --------------------------------------------------------------
    # 6. Erfolgsmeldung
    # --------------------------------------------------------------
    - name: Erfolgsmeldung
      debug:
        msg: "Desktopstarter für uxplay (mit Terminal) wurde auf der Desktop aller Benutzer erstellt."
