---
# ======================================================================
# Playbook: uxplay-desktop-button.yml
# Zweck:    Erstellt Desktopstarter für uxplay (AirPlay Receiver)
#           auf allen realen Benutzerkonten (UID >= 1000, kein nobody)
# ======================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_icon: "/usr/share/icons/hicolor/128x128/apps/uxplay.png"

  tasks:

    # --------------------------------------------------------------
    # 1. Rohdaten aus /etc/passwd holen
    # --------------------------------------------------------------
    - name: Lese alle Benutzer aus /etc/passwd
      command: getent passwd
      register: passwd_entries
      changed_when: false

    # --------------------------------------------------------------
    # 2. Filtern nach echten Benutzern (UID >= 1000, kein nobody)
    # --------------------------------------------------------------
    - name: Filtere reale Benutzer mit Home-Verzeichnis
      set_fact:
        ansible_users: >-
          {{
            passwd_entries.stdout_lines
            | map('split', ':')
            | selectattr('2', 'int', '>=', 1000)
            | selectattr('0', 'ne', 'nobody')
            | selectattr('5', 'match', '^/home/')
            | map('community.general.dict_kv', ['name', 'home'], [0,5])
            | list
          }}

    - name: Zeige gefundene Benutzer
      debug:
        var: ansible_users

    # --------------------------------------------------------------
    # 3. Desktop-Verzeichnisse sicherstellen
    # --------------------------------------------------------------
    - name: Stelle sicher, dass Desktop-Verzeichnisse existieren
      file:
        path: "{{ item.home }}/Desktop"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    # --------------------------------------------------------------
    # 4. Desktopstarter anlegen (Terminalstart)
    # --------------------------------------------------------------
    - name: Erstelle uxplay-Starter auf dem Desktop
      copy:
        dest: "{{ item.home }}/Desktop/uxplay-terminal.desktop"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- /usr/bin/uxplay -n {{ ansible_hostname }} -nh
          Icon={{ uxplay_icon }}
          Terminal=false
          StartupNotify=true
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "0755"
      loop: "{{ ansible_users }}"

    # --------------------------------------------------------------
    # 5. Ausgabe
    # --------------------------------------------------------------
    - name: Erfolgsmeldung
      debug:
        msg: "Desktopstarter für uxplay wurde auf allen Benutzer-Desktops erstellt."

