---
# ======================================================================
# Playbook: uxplay-global-desktop-button.yml
# Zweck:    Erstellt systemweiten Starter für uxplay auf Cinnamon-Desktops
# ======================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    uxplay_icon: "/usr/share/icons/hicolor/128x128/apps/uxplay.png"
    desktop_entry_system: "/usr/share/applications/uxplay-terminal.desktop"
    desktop_entry_skel: "/etc/skel/Schreibtisch/uxplay-terminal.desktop"
    uxplay_exec: "/usr/bin/uxplay -n {{ ansible_hostname }} -nh"

  tasks:

    # --------------------------------------------------------------
    # 1. Icon ins System kopieren
    # --------------------------------------------------------------
    - name: Kopiere uxplay-Icon
      ansible.builtin.copy:
        src: "files/uxplay.png"
        dest: "{{ uxplay_icon }}"
        mode: "0644"

    # --------------------------------------------------------------
    # 2. Systemweiten Starter im Menü anlegen
    # --------------------------------------------------------------
    - name: Erstelle systemweiten uxplay-Starter
      ansible.builtin.copy:
        dest: "{{ desktop_entry_system }}"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- bash -c "{{ uxplay_exec }}; echo; echo 'Drücken Sie [Enter], um das Terminal zu schließen...'; read"
          Icon={{ uxplay_icon }}
          Terminal=false
          Categories=AudioVideo;Network;
          StartupNotify=true
        mode: "0644"

    # --------------------------------------------------------------
    # 3. Erstelle Schreibtisch-Verzeichnis in /etc/skel falls nötig
    # --------------------------------------------------------------
    - name: Stelle sicher, dass /etc/skel/Schreibtisch existiert
      ansible.builtin.file:
        path: /etc/skel/Schreibtisch
        state: directory
        mode: "0755"

    # --------------------------------------------------------------
    # 4. Starter in /etc/skel ablegen (für neue Benutzer)
    # --------------------------------------------------------------
    - name: Starter in /etc/skel ablegen
      ansible.builtin.copy:
        dest: "{{ desktop_entry_skel }}"
        content: |
          [Desktop Entry]
          Type=Application
          Name=AirPlay Receiver (Terminal)
          Comment=Starte uxplay im Terminal
          Exec=gnome-terminal -- bash -c "{{ uxplay_exec }}; echo; echo 'Drücken Sie [Enter], um das Terminal zu schließen...'; read"
          Icon={{ uxplay_icon }}
          Terminal=false
          StartupNotify=true
          X-GNOME-UsesNotifications=true
          X-AppStream-Ignore=true
        mode: "0755"

    # --------------------------------------------------------------
    # 5. Starter auf Schreibtischen bestehender Benutzer anlegen
    # --------------------------------------------------------------
    - name: Kopiere Starter auf Schreibtische bestehender Benutzer
      ansible.builtin.shell: |
        for dir in /home/*; do
          if [ -d "$dir/Schreibtisch" ] && [ -w "$dir/Schreibtisch" ]; then
            cp "{{ desktop_entry_skel }}" "$dir/Schreibtisch/uxplay-terminal.desktop"
            chown $(basename "$dir"):$(basename "$dir") "$dir/Schreibtisch/uxplay-terminal.desktop"
            chmod +x "$dir/Schreibtisch/uxplay-terminal.desktop"
          fi
        done
      args:
        executable: /bin/bash
      ignore_errors: true

    # --------------------------------------------------------------
    # 6. Vertrauen in Cinnamon aktivieren (kein Sicherheitsdialog)
    # --------------------------------------------------------------
    - name: Markiere alle uxplay-Starter als vertrauenswürdig
      ansible.builtin.shell: |
        for file in /home/*/Schreibtisch/uxplay-terminal.desktop; do
          if [ -f "$file" ]; then
            gio set "$file" "metadata::trusted" true || true
          fi
        done
      args:
        executable: /bin/bash
      ignore_errors: true
      
    # --------------------------------------------------------------
    # 7. Setze Besitzrechte und Sichtbarkeit korrekt
    # --------------------------------------------------------------
    - name: Korrigiere Besitzrechte und Berechtigungen auf Benutzer-Schreibtischen
      ansible.builtin.shell: |
        for dir in /home/*; do
          if [ -d "$dir/Schreibtisch" ]; then
            chown $(basename "$dir"):$(basename "$dir") "$dir/Schreibtisch/uxplay-terminal.desktop" 2>/dev/null || true
            chmod +x "$dir/Schreibtisch/uxplay-terminal.desktop" 2>/dev/null || true
          fi
        done
      args:
        executable: /bin/bash
      ignore_errors: true

    # --------------------------------------------------------------
    # 8. Nemo-Desktop neu laden, damit Icons erscheinen
    # --------------------------------------------------------------
    - name: Aktualisiere Desktop-Ansicht für angemeldete Benutzer
      ansible.builtin.shell: |
        for user in $(who | awk '{print $1}' | sort -u); do
          sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $user)/bus nemo-desktop --quit 2>/dev/null || true
          sleep 1
          sudo -u "$user" DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u $user)/bus nemo-desktop --no-desktop 2>/dev/null || true
        done
      args:
        executable: /bin/bash
      ignore_errors: true
