---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Ensure uxplay service is running
    ansible.builtin.systemd:
      name: uxplay
      state: started
      enabled: true
      daemon_reload: true
