---
# ================================================================
# Playbook: uxplay-xprofile.yml
# Zweck:    AirPlay-Empfänger (uxplay) beim Login für alle Nutzer starten
#           Funktioniert zuverlässig mit DISPLAY, DBus, PulseAudio.
# ================================================================

- hosts: localhost
  connection: local
  become: true

  vars:
    room_name: "{{ ansible_hostname }}"  # Name im AirPlay-Menü
    uxplay_path: "/usr/bin/uxplay"

  tasks:

  - name: Entferne systemweiten uxplay-Dienst, falls vorhanden
    ansible.builtin.file:
      path: /etc/systemd/system/uxplay.service
      state: absent

  - name: Entferne systemd-user Unit, falls vorhanden
    ansible.builtin.file:
      path: /etc/systemd/user/uxplay.service
      state: absent

  - name: Stelle sicher, dass ~/.xprofile existiert (bestehende Nutzer)
    ansible.builtin.file:
      path: "{{ item }}/.xprofile"
      state: touch
      owner: "{{ item | basename }}"
      group: "{{ item | basename }}"
      mode: "0755"
    loop: "{{ lookup('ansible.builtin.pipe','getent passwd | cut -d: -f6 | grep -v /nonexistent', wantlist=True) }}"

  - name: Füge uxplay Startbefehl in ~/.xprofile ein (bestehende Nutzer)
    ansible.builtin.lineinfile:
      path: "{{ item }}/.xprofile"
      line: "{{ uxplay_path }} -n {{ room_name }} -nh &"
      state: present
      insertafter: EOF
      create: yes
    loop: "{{ lookup('ansible.builtin.pipe','getent passwd | cut -d: -f6 | grep -v /nonexistent', wantlist=True) }}"

  - name: Stelle sicher, dass /etc/skel/.xprofile existiert (neue Nutzer)
    ansible.builtin.file:
      path: /etc/skel/.xprofile
      state: touch
      owner: root
      group: root
      mode: "0755"

  - name: Füge uxplay Startbefehl in /etc/skel/.xprofile ein (neue Nutzer)
    ansible.builtin.lineinfile:
      path: /etc/skel/.xprofile
      line: "{{ uxplay_path }} -n {{ room_name }} -nh &"
      state: present
      insertafter: EOF
