---
# Dieses Playbook installiert die aktuelle Version von Veyon. Das Debian-Paket des Herstellers 
# ist weder 端ber die Debian-Repositories noch 端ber Flathub verf端gbar und kann daher nur 
# direkt beim Hersteller bezogen werden.

- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: Update repositories cache
    ansible.builtin.apt:
      update_cache: yes
      state: latest

  - name: Deinstalliere die alte Veyon-Version aus dem Debian-Repository
    package:
      name: 
        - libveyon-core
        - veyon-configurator
        - veyon-master
        - veyon-plugins
        - veyon-service
      state: absent

  - name: Pr端fe, welche Pakete vorhanden sind
    package_facts:
      manager: apt

  - name: Erzeuge das Verzeichnis packages, falls es noch nicht existiert
    ansible.builtin.file:
      path: /home/administrator/packages
      state: directory
      mode: '0755'

  - name: Kopiere die Installationsdatei von Veyon in ein lokales Verzeichnis des Administrators
    ansible.builtin.get_url:
      url: https://github.com/veyon/veyon/releases/download/v4.9.3/veyon_4.9.3.0-debian.12_amd64.deb
      dest: /home/administrator/packages/veyon_4.9.3.0-debian.12_amd64.de
      mode: '0644'
    when: '"veyon" not in ansible_facts.packages'

  - name: Installiere die aktuelle Version des Programms Veyon
    ansible.builtin.apt:
      deb: /home/administrator/packages/veyon_4.9.3.0-debian.12_amd64.deb
    when: '"veyon" not in ansible_facts.packages'

  - name: Entferne die Installationsdatei von Veyon
    ansible.builtin.file:
      path: /home/administrator/packages/veyon_4.9.3.0-debian.12_amd64.deb
      state: absent

  - name: Lade Veyon Konfigurationsdatei herunter
    get_url:
      url: https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyon-settings-HG-Linux.json
      dest: /tmp/veyon-settings-HG-Linux.json
      mode: '0644'

  - name: Lade Veyon Netzwerkobjekte CSV herunter
    get_url:
      url: https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/raum311-import-file.csv
      dest: /tmp/raum311-import-file.csv
      mode: '0644'

  - name: Importiere Veyon Konfigurationsdatei
    command: sudo veyon-cli config import /tmp/veyon-settings-HG-Linux.json
 
  - name: Importiere Veyon Netzwerkobjekte
    command: sudo veyon-cli networkobjects import /tmp/raum311-import-file.csv format "%location%,%name%,%host%,%mac%"
