---
# Dieses Playbook installiert die aktuelle Version von Veyon.
# Das Debian-Paket des Herstellers ist weder über die Debian-Repositories
# noch über Flathub verfügbar und kann daher nur direkt beim Hersteller bezogen werden.

- hosts: localhost
  connection: local
  become: true

  vars:
    room: "Raum312"

  pre_tasks:
    - name: Abbrechen, falls kein Debian-System vorliegt
      fail:
        msg: "Dieses Playbook ist nur für Debian-Systeme vorgesehen."
      when: ansible_facts['os_family'] != "Debian"

  tasks:

  # --------------------------------------------------------------------------
  # Konfigurations- und Netzobjekte importieren
  # --------------------------------------------------------------------------
  - name: Lade die Veyon-Konfigurationsdatei herunter
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/veyon-settings-HG-Linux.json"
      dest: /tmp/veyon-settings-HG-Linux.json
      mode: '0644'

  - name: Lade die Veyon Netzwerkobjekte CSV herunter
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/{{ room }}-import-file.csv"
      dest: /tmp/{{ room }}-import-file.csv
      mode: '0644'
      
  # Die Veyon-Netzwerkobjekte-Datei ist ein direkter Export aus IServ. Sie enthält 4 Spalten zu viel
      
  - name: Kürze die CSV-Datei auf relevante Spalten
    shell: |
      cut -d';' -f1-4 /tmp/{{ room }}-import-file.csv > /tmp/{{ room }}-import-file-trimmed.csv
    args: 
      executable: /bin/bash

  - name: Lade den öffentlichen Schlüssel herunter
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/{{ room }}_public_key.pem"
      dest: /tmp/{{ room }}_public_key.pem
      mode: '0644'

  - name: Lade den privaten Schlüssel herunter
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/{{ room }}_private_key.pem"
      dest: /tmp/{{ room }}_private_key.pem
      mode: '0600'
      
  - name: Importiere die Veyon-Konfiguration und die Netzwerkobjekte
    become: yes
    shell: |
      set -e
      veyon-cli config import /tmp/veyon-settings-HG-Linux.json
      veyon-cli networkobjects clear
      veyon-cli networkobjects import /tmp/{{ room }}-import-file-trimmed.csv format "%name%;%location%;%host%;%mac%"
      veyon-cli authkeys import {{ room }}/public /tmp/{{ room }}_public_key.pem
      veyon-cli authkeys setaccessgroup {{ room }}/public schueler.innen
      veyon-cli authkeys import {{ room }}/private /tmp/{{ room }}_private_key.pem
      veyon-cli authkeys setaccessgroup {{ room }}/private lehrer.innen
    args: 
      executable: /bin/bash
    changed_when: false

  # --------------------------------------------------------------------------
  # Aufräumen
  # --------------------------------------------------------------------------
  - name: Entferne temporäre Veyon-Dateien
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - /tmp/veyon-settings-HG-Linux.json
      - /tmp/{{ room }}-import-file.csv
      - /tmp/{{ room }}-import-file-trimmed.csv
      - /tmp/{{ room }}_public_key.pem
      - /tmp/{{ room }}_private_key.pem
