---
# Dieses Playbook installiert die aktuelle Version von Veyon. Das Debian-Paket des Herstellers 
# ist weder über die Debian-Repositories noch über Flathub verfügbar und kann daher nur 
# direkt beim Hersteller bezogen werden.

- hosts: localhost
  connection: local
  become: true

  vars:
    veyon_version: "4.9.7.0-debian.12_amd64"
    veyon_folder: "4.9.7"
  
  tasks:

  - name: Deaktiviere Wayland in GDM3-Konfiguration
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/gdm3/daemon.conf
      regexp: '^#?WaylandEnable='
      line: 'WaylandEnable=false'
      state: present
    notify: Restart GDM


  - name: Update repositories cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Deinstalliere die alte Veyon-Version aus dem Debian-Repository
    package:
      name: 
        - libveyon-core
        - veyon-configurator
        - veyon-master
        - veyon-plugins
        - veyon-service
      state: absent

  - name: Prüfe, welche Pakete vorhanden sind
    package_facts:
      manager: apt

  - name: Erzeuge das Verzeichnis packages, falls es noch nicht existiert
    ansible.builtin.file:
      path: /home/administrator/packages
      state: directory
      mode: '0755'

  - name: Kopiere die Installationsdatei von Veyon in ein lokales Verzeichnis des Administrators
    ansible.builtin.get_url:
      url: "https://github.com/veyon/veyon/releases/download/v{{veyon_folder}}/veyon_{{ veyon_version }}.deb"
      dest: "/home/administrator/packages/veyon_{{ veyon_version }}.deb"
      mode: '0644'
    when: '"veyon" not in ansible_facts.packages'

  - name: Installiere die aktuelle Version des Programms Veyon
    ansible.builtin.apt:
      deb: /home/administrator/packages/veyon_{{ veyon_version }}.deb
      state: present
    when: ansible_facts['distribution'] == "Debian"

  - name: Lade die Veyon Konfigurationsdatei herunter
    get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/veyon-settings-HG-Linux.json"
      dest: /tmp/veyon-settings-HG-Linux.json
      mode: '0644'

  - name: Lade Veyon Netzwerkobjekte CSV herunter
    get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/device-import-file.csv"
      dest: /tmp/device-import-file.csv
      mode: '0644'

  - name: Lade den öffentlichen Schlüssel herunter
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/hvoss71/ansible_desktop/main/veyonfiles/PC-Raum311_public_key.pem"
      dest: "/tmp/PC-Raum311_public_key.pem"
      mode: '0644'
 
  - name: Importiere die Konfigurationsdateien über die Kommandozeilenschnittstelle
    become: yes
    shell: |
      set -e
      veyon-cli config import /tmp/veyon-settings-HG-Linux.json
      veyon-cli networkobjects clear
      veyon-cli networkobjects import /tmp/device-import-file.csv format "%name%;%location%;%host%;%mac%"
      veyon-cli authkeys import PC-Raum311/public /tmp/PC-Raum311_public_key.pem
      veyon-cli authkeys setaccessgroup PC-Raum311/public schueler.innen

      
  - name: Entferne temporäre Veyon-Dateien
    file:
      path: "{{ item }}"
      state: absent
    loop:
    - /tmp/veyon-settings-HG-Linux.json
    - /tmp/device-import-file.csv
    - /tmp/PC-Raum311_public_key.pem
    - /home/administrator/packages/veyon_{{ veyon_version }}.deb

  handlers:
    - name: Restart GDM
      become: yes
      ansible.builtin.systemd:
        name: gdm3
        state: restarted
